version: '3.9'
services:
  agones-mc:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - backup
      - --host=minecraft
      - --gcp-bucket-name=${GCP_BUCKET_NAME}
      - --initial-delay=60s

    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /root/.config/gcloud/application_default_credentials.json
      NAME: ${NAME}
    volumes:
      - mc-world:/data
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/root/.config/gcloud/application_default_credentials.json

  minecraft:
    image: itzg/minecraft-server
    environment:
      EULA: 'TRUE'
    volumes:
      - mc-world:/data

volumes:
  mc-world:
