version: '3.9'
services:
  agones-mc:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - load
      - --gcp-bucket-name=${GCP_BUCKET_NAME}

    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /root/.config/gcloud/application_default_credentials.json
      NAME: ${NAME}
      BACKUP: ${BEDROCK_BACKUP}
    volumes:
      - mc-world:/data
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/root/.config/gcloud/application_default_credentials.json

  minecraft:
    image: saulmaldonado/minecraft-bedrock-server
    environment:
      EULA: 'TRUE'
      WORLD: '/data/world.zip'
    entrypoint:
      [
        '/bin/bash',
        '-c',
        'sleep 30; /usr/local/bin/entrypoint-demoter --match /data --debug --stdin-on-term stop /opt/bedrock-entry.sh',
      ]
    volumes:
      - mc-world:/data

volumes:
  mc-world:
