version: '3.9'
services:
  agones-mc:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - load
      - --gcp-bucket-name=${GCP_BUCKET_NAME}
    network_mode: host

    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /root/.config/gcloud/application_default_credentials.json
      NAME: ${NAME}
    volumes:
      - mc-world:/data
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/root/.config/gcloud/application_default_credentials.json

  minecraft:
    image: itzg/minecraft-server
    network_mode: host
    environment:
      EULA: 'TRUE'
      WORLD: '/data/world.zip'
    entrypoint: ['/bin/bash', '-c', 'sleep 30; /start']
    volumes:
      - mc-world:/data

  sdk:
    build:
      context: .
      dockerfile: Dockerfile.sdk
    network_mode: host
    command: ./sdk-server.linux.amd64 --local --file /example/mc-server-load.yml
    volumes:
      - $PWD/example/mc-server-load.yml:/example/mc-server-load.yml

volumes:
  mc-world:
